[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "youtube-summarizer-llm"
version = "0.1.0"
description = "YouTube content analyzer with transcript summarization"
requires-python = ">=3.8"
dependencies = [
    "youtube-transcript-api",
]